services:
  orchestrator:
    container_name: orchestrator-app
    build:
      context: .
      network: host
    env_file:
      - .env
    command: node src/$ORCHESTRATOR_SCRIPT
    # networks:
    #   - experiment-net
    ports:
      - $UDP_PORT:$UDP_PORT/udp
    volumes:
      - ./notebook/data:/app/src/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G