services:
  orchestrator:
    container_name: orchestrator-app
    build:
      context: .
    env_file:
      - .env
    command: node src/${ORCHESTRATOR_SCRIPT}
    # networks:
    #   - experiment-net
    ports:
      - "${UDP_PORT}:${UDP_PORT}/udp"
    network_mode: host
    volumes:
      - ./notebook/data:/app/src/data
    cpus: '2.0'
    mem_limit: 2g